# Form implementation generated from reading ui file 'kurs5.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewWindow(object):
    def setupUi(self, ViewWindow):
        ViewWindow.setObjectName("ViewWindow")
        ViewWindow.resize(388, 500)
        ViewWindow.setMinimumSize(QtCore.QSize(388, 500))
        ViewWindow.setMaximumSize(QtCore.QSize(388, 500))
        ViewWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=ViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 421, 501))
        self.label_3.setStyleSheet("border-image: url(./картинки/df26c3111893819.600a2261192bf.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("df26c3111893819.600a2261192bf.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.pushButton_2.setStyleSheet("\n"
"border-image: url(./картинки/аппппппкы.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("аппппппкы.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setAutoRepeatDelay(100)
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 70, 311, 391))
        self.listWidget.setMinimumSize(QtCore.QSize(311, 391))
        self.listWidget.setMaximumSize(QtCore.QSize(311, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.listWidget.raise_()
        ViewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ViewWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewWindow)

    def retranslateUi(self, ViewWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewWindow.setWindowTitle(_translate("ViewWindow", "MainWindow"))
        self.label.setText(_translate("ViewWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">View</span></p></body></html>"))
